### ISSUE TITLE
Getting errors on retrieving new messages

### ISSUE THREAD

**Issue by weirdGuy** [datopian/ourbot#18]
Erroring on retrieving new message
Happens on new message, cause not correct handling of pattern search
Need to add if-statement for checking if array with pattern is null
```
ERROR TypeError: Cannot read property '0' of null
    at TextListener.callback (E:\gitterbot\scripts\main.coffee:18:30)
    at E:\gitterbot\node_modules\hubot\src\listener.coffee:53:21
    at allDone (E:\gitterbot\node_modules\hubot\src\middleware.coffee:35:16)
    at E:\gitterbot\node_modules\hubot\node_modules\async\lib\async.js:274:13
    at Object.async.eachSeries (E:\gitterbot\node_modules\hubot\node_modules\async\lib\async.js:142:20)
    at Object.async.reduce (E:\gitterbot\node_modules\hubot\node_modules\async\lib\async.js:268:15)
    at E:\gitterbot\node_modules\hubot\src\middleware.coffee:39:24
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
TypeError: Cannot read property '0' of null
    at TextListener.callback (E:\gitterbot\scripts\main.coffee:18:30)
    at E:\gitterbot\node_modules\hubot\src\listener.coffee:53:21
    at allDone (E:\gitterbot\node_modules\hubot\src\middleware.coffee:35:16)
    at E:\gitterbot\node_modules\hubot\node_modules\async\lib\async.js:274:13
    at Object.async.eachSeries (E:\gitterbot\node_modules\hubot\node_modules\async\lib\async.js:142:20)
    at Object.async.reduce (E:\gitterbot\node_modules\hubot\node_modules\async\lib\async.js:268:15)
    at E:\gitterbot\node_modules\hubot\src\middleware.coffee:39:24
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by weirdGuy** [comment]
Fixed
