### ISSUE TITLE
Script is erroring if coffeescript is added as dependency in package.json

### ISSUE THREAD

**Issue by zelima** [datopian/ourbot#5]
```
ReferenceError: no id given to create an object: null, [object Object<token,id>]
  at GitterClient.GitterObject [as constructor] (/home/zelima/Desktop/atomatic/other/ourbot/node_modules/hubot-gitter2/src/GitterObject.coffee:107:11)
  at new GitterClient (/home/zelima/Desktop/atomatic/other/ourbot/node_modules/hubot-gitter2/src/GitterClient.coffee:34:5)
  at Function.GitterObject.factory (/home/zelima/Desktop/atomatic/other/ourbot/node_modules/hubot-gitter2/src/GitterObject.coffee:67:45)
  at Function.GitterClient.factory (/home/zelima/Desktop/atomatic/other/ourbot/node_modules/hubot-gitter2/src/GitterClient.coffee:24:26)
  at HubotGitter2Adapter.gitterClient (/home/zelima/Desktop/atomatic/other/ourbot/node_modules/hubot-gitter2/src/HubotGitter2Adapter.coffee:120:31)
  at HubotGitter2Adapter.run (/home/zelima/Desktop/atomatic/other/ourbot/node_modules/hubot-gitter2/src/HubotGitter2Adapter.coffee:82:11)
  at Robot.run (/home/zelima/Desktop/atomatic/other/ourbot/node_modules/hubot/src/robot.coffee:590:14)
  at Object.<anonymous> (/home/zelima/Desktop/atomatic/other/ourbot/node_modules/hubot/bin/hubot:182:11)
  at Object.<anonymous> (/home/zelima/Desktop/atomatic/other/ourbot/node_modules/hubot/bin/hubot:185:4)
  at Module._compile (module.js:571:32)
  at Object.exports.run (/home/zelima/Desktop/atomatic/other/ourbot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:173:23)
  at compileScript (/home/zelima/Desktop/atomatic/other/ourbot/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
  at compilePath (/home/zelima/Desktop/atomatic/other/ourbot/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
  at Object.exports.run (/home/zelima/Desktop/atomatic/other/ourbot/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
  at Object.<anonymous> (/home/zelima/Desktop/atomatic/other/ourbot/node_modules/coffee-script/bin/coffee:7:41)
  at Module._compile (module.js:571:32)
  at Object.Module._extensions..js (module.js:580:10)
  at Module.load (module.js:488:32)
  at tryModuleLoad (module.js:447:12)
  at Function.Module._load (module.js:439:3)
  at Module.runMain (module.js:605:10)
  at run (bootstrap_node.js:420:7)
  at startup (bootstrap_node.js:139:9)
  at bootstrap_node.js:535:3
```

@weirdGuy says:
> it happens always if coffeescript added as dependency in package.json, cause some modules in Gitter adapter little buggy
I've been facing this too
there is mistake in code of adapter in object creation huafu/hubot-gitter2#10

As a solution for now, we need to remofe coffescript form package.json and mention to install it  manually

**Comment by weirdGuy** [comment]
This one issue have been fixed by removing coffee-script from package.json, also added manual installation of coffee in readme

**Comment by rufuspollock** [comment]
@weirdGuy why do we need manual installation of coffeescript? Can you please explain.

**Comment by weirdGuy** [comment]
FIXED. Changed config.json
